
FROM ubuntu:16.04
LABEL maintainer="eivind@xal.no"

RUN  apt-get --yes update \
 &&  apt-get --yes install \
        build-essential \
        curl \
        git \
        python \
        wget \
 && apt-get --yes clean

